"""initial skjema

Hele datamodellen fra backend_spec §1-§11. Forskningstabellene legges i et
eget Postgres-skjema (`research`) fra dag én - adskillelsen er dyr aa
ettermontere. Paa SQLite (tester) finnes ikke skjemaer; der oversetter
migrations/env.py `research` til None via schema_translate_map.

Revision ID: d21e5f8ac782
Revises:
Create Date: 2026-08-02 12:13:09.224445
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd21e5f8ac782'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RESEARCH_SCHEMA = "research"


def _has_schemas() -> bool:
    return op.get_bind().dialect.name != "sqlite"


def upgrade() -> None:
    if _has_schemas():
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{RESEARCH_SCHEMA}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('device_model', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('forwarded_at', sa.DateTime(), nullable=True),
    sa.Column('forward_error', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_received_at'), 'feedback', ['received_at'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=64), nullable=False),
    sa.Column('consent_type', sa.Enum('training', 'hunt', name='resulttype', native_enum=False, length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudonym_id', 'consent_type', name='uq_consent_subject_type'),
    schema='research'
    )
    op.create_index(op.f('ix_research_consents_pseudonym_id'), 'consents', ['pseudonym_id'], unique=False, schema='research')
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index(op.f('ix_research_deletion_requests_pseudonym_id'), 'deletion_requests', ['pseudonym_id'], unique=False, schema='research')
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=64), nullable=False),
    sa.Column('session_ref', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('result_type', sa.Enum('training', 'hunt', name='resulttype', native_enum=False, length=16), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index(op.f('ix_research_records_captured_at'), 'records', ['captured_at'], unique=False, schema='research')
    op.create_index(op.f('ix_research_records_pseudonym_id'), 'records', ['pseudonym_id'], unique=False, schema='research')
    op.create_index(op.f('ix_research_records_session_ref'), 'records', ['session_ref'], unique=False, schema='research')
    op.create_table('search_quarantines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('account', 'ip', name='quarantinescope', native_enum=False, length=16), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=False),
    sa.Column('quarantined_until', sa.DateTime(), nullable=True),
    sa.Column('offense_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'subject', name='uq_quarantine_scope_subject')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=24), nullable=False),
    sa.Column('display_name_status', sa.Enum('pending', 'approved', 'rejected', name='namestatus', native_enum=False, length=16), nullable=False),
    sa.Column('display_name_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('home_kommune', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('findable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', 'email', name='provider', native_enum=False, length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('backups',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('client_ts', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='platform', native_enum=False, length=16), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_token')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('failed_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('series_id', sa.String(length=36), nullable=True),
    sa.Column('tag', sa.Enum('ocr_match', 'ocr_mismatch', 'rejected', name='failedtag', native_enum=False, length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('core_version', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=True),
    sa.Column('image_legacy', sa.LargeBinary(), nullable=True),
    sa.Column('detected_scores', sa.JSON(), nullable=False),
    sa.Column('ocr_scores', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_analyses_series_id'), 'failed_analyses', ['series_id'], unique=False)
    op.create_index(op.f('ix_failed_analyses_submitted_at'), 'failed_analyses', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_failed_analyses_tag'), 'failed_analyses', ['tag'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('addressee_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'blocked', name='friendshipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('requester_id <> addressee_id', name='ck_friendship_not_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_index(op.f('ix_friendships_status'), 'friendships', ['status'], unique=False)
    op.create_table('research_sharing_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('share_species', sa.Boolean(), nullable=False),
    sa.Column('share_date', sa.Boolean(), nullable=False),
    sa.Column('share_shot_situation', sa.Boolean(), nullable=False),
    sa.Column('position_granularity', sa.Enum('none', 'kommune', 'fylke', 'exact', name='positiongranularity', native_enum=False, length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('weapon_id', sa.String(length=36), nullable=True),
    sa.Column('ammo_name', sa.String(length=64), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('LIGGENDE', 'SITTENDE', 'KNESTAENDE', 'STAAENDE', name='position', native_enum=False, length=16), nullable=False),
    sa.Column('modifier', sa.Enum('UTEN', 'ANLEGG', 'REIM', name='posmodifier', native_enum=False, length=16), nullable=False),
    sa.Column('corrected', sa.Boolean(), nullable=False),
    sa.Column('season_key', sa.String(length=16), nullable=False),
    sa.Column('sum_decimal', sa.Float(), nullable=False),
    sa.Column('sum_integer', sa.Integer(), nullable=False),
    sa.Column('shot_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_season_key'), 'series', ['season_key'], unique=False)
    op.create_index(op.f('ix_series_ts'), 'series', ['ts'], unique=False)
    op.create_index(op.f('ix_series_user_id'), 'series', ['user_id'], unique=False)
    op.create_index(op.f('ix_series_weapon_id'), 'series', ['weapon_id'], unique=False)
    op.create_table('sharing_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('share_phone', sa.Boolean(), nullable=False),
    sa.Column('share_home_kommune', sa.Boolean(), nullable=False),
    sa.Column('share_shots_total', sa.Boolean(), nullable=False),
    sa.Column('share_shots_season', sa.Boolean(), nullable=False),
    sa.Column('share_avg_score', sa.Boolean(), nullable=False),
    sa.Column('share_trend', sa.Boolean(), nullable=False),
    sa.Column('share_kills', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('jakt', 'skytter', name='teamkind', native_enum=False, length=16), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leader_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('leader_id', sa.String(length=36), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Enum('pending', 'cancelled_leader_active', 'leader_demoted', name='challengeoutcome', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leader_challenges_deadline_at'), 'leader_challenges', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_leader_challenges_team_id'), 'leader_challenges', ['team_id'], unique=False)
    op.create_table('pending_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_messages_created_at'), 'pending_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_messages_user_id'), 'pending_messages', ['user_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('r_rel', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('decimal', sa.Float(), nullable=False),
    sa.Column('integer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'idx', name='uq_shot_series_idx')
    )
    op.create_index(op.f('ix_shots_series_id'), 'shots', ['series_id'], unique=False)
    op.create_table('team_elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Enum('pending', 'elected', 'cancelled', 'expired', name='electionoutcome', native_enum=False, length=24), nullable=False),
    sa.Column('elected_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['elected_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_elections_closes_at'), 'team_elections', ['closes_at'], unique=False)
    op.create_index(op.f('ix_team_elections_team_id'), 'team_elections', ['team_id'], unique=False)
    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('target_kind', sa.Enum('email', 'phone', name='invitetarget', native_enum=False, length=16), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('delivery_status', sa.Enum('pending', 'sent', 'failed', 'accepted', name='deliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('delivery_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invites_team_id'), 'team_invites', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_invites_token'), 'team_invites', ['token'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('member', 'leader', name='teamrole', native_enum=False, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('team_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['election_id'], ['team_elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'voter_id', name='uq_vote_election_voter')
    )
    op.create_index(op.f('ix_team_votes_election_id'), 'team_votes', ['election_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_votes_election_id'), table_name='team_votes')
    op.drop_table('team_votes')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invites_token'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_team_id'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_team_elections_team_id'), table_name='team_elections')
    op.drop_index(op.f('ix_team_elections_closes_at'), table_name='team_elections')
    op.drop_table('team_elections')
    op.drop_index(op.f('ix_shots_series_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_pending_messages_user_id'), table_name='pending_messages')
    op.drop_index(op.f('ix_pending_messages_created_at'), table_name='pending_messages')
    op.drop_table('pending_messages')
    op.drop_index(op.f('ix_leader_challenges_team_id'), table_name='leader_challenges')
    op.drop_index(op.f('ix_leader_challenges_deadline_at'), table_name='leader_challenges')
    op.drop_table('leader_challenges')
    op.drop_table('teams')
    op.drop_table('sharing_preferences')
    op.drop_index(op.f('ix_series_weapon_id'), table_name='series')
    op.drop_index(op.f('ix_series_user_id'), table_name='series')
    op.drop_index(op.f('ix_series_ts'), table_name='series')
    op.drop_index(op.f('ix_series_season_key'), table_name='series')
    op.drop_table('series')
    op.drop_table('research_sharing_preferences')
    op.drop_index(op.f('ix_friendships_status'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_failed_analyses_tag'), table_name='failed_analyses')
    op.drop_index(op.f('ix_failed_analyses_submitted_at'), table_name='failed_analyses')
    op.drop_index(op.f('ix_failed_analyses_series_id'), table_name='failed_analyses')
    op.drop_table('failed_analyses')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('backups')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('search_quarantines')
    op.drop_index(op.f('ix_research_records_session_ref'), table_name='records', schema='research')
    op.drop_index(op.f('ix_research_records_pseudonym_id'), table_name='records', schema='research')
    op.drop_index(op.f('ix_research_records_captured_at'), table_name='records', schema='research')
    op.drop_table('records', schema='research')
    op.drop_index(op.f('ix_research_deletion_requests_pseudonym_id'), table_name='deletion_requests', schema='research')
    op.drop_table('deletion_requests', schema='research')
    op.drop_index(op.f('ix_research_consents_pseudonym_id'), table_name='consents', schema='research')
    op.drop_table('consents', schema='research')
    op.drop_index(op.f('ix_feedback_received_at'), table_name='feedback')
    op.drop_table('feedback')
    if _has_schemas():
        op.execute(f'DROP SCHEMA IF EXISTS "{RESEARCH_SCHEMA}"')
    # ### end Alembic commands ###
